# Generated by Django 5.0.6 on 2024-06-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="просмотры"),
        ),
    ]
