# Generated by Django 4.2.2 on 2024-07-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("can_unpublish_product", "Can unpublish product"),
                    ("change_product_description", "Can change product description"),
                    ("change_product_category", "Can change product category"),
                ),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
